### ISSUE TITLE
REPAIR twice in molecular synthesis laboratory

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#16]
>repair
You don't see anything in need of repair.

Maybe "You already fixed the service panel. You don't want to get too cute." Or something.

**Comment by andrewschultz** [comment]
Also see the circuit breakers in Stairway, First Level.

**Comment by dhakajack** [comment]
The repair action was a little kludgy to start off with. I ended up rewriting the action itself in a pretty narrow way since now that the story is written, I know the only two items that need to be considered are the servo and the circuit breakers. There are now custom messages for repeated attempts on both.
