### ISSUE TITLE
Ending tweaks

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#20]
"After a couple hours of discussion and some blood tests, the colonel is convinced and orders that the airlock doors be unsealed, permitting you to exit."

While I like the line "you relate everything that has happened, leaving out, for now, some of the details suggested by Lucky and the mouse." it would still be nice to read what they had to say about the outside world for a sentence or two.

Also "You request to speak" -> "You ask to speak" sounds a bit more natural.

And should "under MIT license." be "under the MIT license."?

**Comment by dhakajack** [comment]
I'm not entirely happy with the ending, but don't have an immediate idea in mind to revise it. One other bit of feedback that I agree with is that the ending comes up suddenly. I would like to pay off the mouse and Lucky more extensively, but am concerned about a text dump at the end. I am a little reluctant to begin addressing events after they leave the airlock because that could go on for quite a while and is really another story (whether it gets written or not, we'll have to see. I often have the intention of writing sequels but so far haven't).
