### ISSUE TITLE
east in corridor right away gives potential spoiler reject

### ISSUE THREAD

**Issue by andrewschultz** [dhakajack/web-cerveaux#21]
>east

Corridor
A white, unfurnished hallway.

Potential exits: west. 
>east
The wall does not budge.
>* should we know that we can budge it yet? Eventually we will, but maybe not now. It contrasts with "can't go that way" if you go back west/west.

**Comment by dhakajack** [comment]
I picked "doesn't budge" because this is the response you get when you try to walk through a closed door. "Can't go" isn't quite right, because you could go, if you opened it first.  I've changed the built-in "can't go" message to to "The wall does not budge", which should address the issue of meta-information.

The arrows do provide a bit of a hint -- i.e., when there is a door that is closed and/or locked and the character has the ability to get through it, an arrow is shown.
